#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
eval "$(anyenv init -)"

export HISTSIZE=8999999
export HISTFILE=~/.zhistory

export PATH=~/bin:$PATH

source ~/.bin/tmuxinator.zsh

export ALTERNATE_EDITOR=""
# alias e='emacsclient -t'
# alias ec='emacsclient -c -n'

export EDITOR=e
